database:
  host: localhost
  port: 5432
  user: postgres
  password: kosty8021
  dbname: ReportsGo
  sslmode: disable

worker:
  concurrency: 10

minio:
  endpoint: localhost:9000
  access_key: minioadmin
  secret_key: minioadmin
  pdf_bucket: reports-pdf
  docx_bucket: reports-docx
  use_ssl: false